"""empty message

Revision ID: 8c102ddd21d8
Revises: ba19a3728c9e
Create Date: 2023-03-30 18:27:51.718186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c102ddd21d8'
down_revision = 'ba19a3728c9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('links', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('links')

    op.create_table('link',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=100), nullable=False),
    sa.Column('url', sa.VARCHAR(length=200), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
